import UIKit
import Flutter
import Engine // This would be the framework generated by gomobile

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  var nativeEngine: EngineEngine?

  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    let controller : FlutterViewController = window?.rootViewController as! FlutterViewController
    let nativeChannel = FlutterMethodChannel(name: "com.anidong.app/native_engine",
                                              binaryMessenger: controller.binaryMessenger)

    nativeChannel.setMethodCallHandler({
      [weak self] (call: FlutterMethodCall, result: @escaping FlutterResult) -> Void in
      guard let self = self else { return }

      switch call.method {
      case "initialize":
        if let args = call.arguments as? [String: Any],
           let dbPath = args["dbPath"] as? String {
          do {
            var err: NSError?
            self.nativeEngine = EngineNewEngine(dbPath, &err)
            if let error = err {
              result(FlutterError(code: "INIT_ERROR", message: error.localizedDescription, details: nil))
            } else {
              result(nil)
            }
          }
        }
      case "getOrCompute":
        if let args = call.arguments as? [String: Any],
           let key = args["key"] as? String,
           let ttl = args["ttlSeconds"] as? Int,
           let taskType = args["taskType"] as? String,
           let input = args["input"] as? FlutterStandardTypedData {

          self.nativeEngine?.getOrCompute(key, ttlSeconds: ttl, taskType: taskType, input: input.data, callback: NativeCallbackWrapper(result: result))
        } else {
          result(FlutterError(code: "INVALID_ARGS", message: "Missing arguments", details: nil))
        }
      case "flushCache":
        self.nativeEngine?.flushCache()
        result(nil)
      case "getStats":
        result(self.nativeEngine?.getStats())
      case "dispose":
        self.nativeEngine?.close()
        self.nativeEngine = nil
        result(nil)
      default:
        result(FlutterMethodNotImplemented)
      }
    })

    GeneratedPluginRegistrant.register(with: self)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}

class NativeCallbackWrapper: NSObject, EngineCallbackProtocol {
    let result: FlutterResult

    init(result: @escaping FlutterResult) {
        self.result = result
    }

    func onSuccess(_ data: Data?) {
        DispatchQueue.main.async {
            self.result(data)
        }
    }

    func onError(_ err: String?) {
        DispatchQueue.main.async {
            self.result(FlutterError(code: "COMPUTE_ERROR", message: err, details: nil))
        }
    }
}
