package com.narmadaweb.anidong

import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugin.common.MethodChannel
import engine.Engine // This would be the class generated by gomobile
import engine.Callback

class MainActivity: FlutterActivity() {
    private val CHANNEL = "com.anidong.app/native_engine"
    private var nativeEngine: Engine? = null

    override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
        super.configureFlutterEngine(flutterEngine)

        MethodChannel(flutterEngine.dartExecutor.binaryMessenger, CHANNEL).setMethodCallHandler { call, result ->
            when (call.method) {
                "initialize" -> {
                    val dbPath = call.argument<String>("dbPath")
                    try {
                        nativeEngine = Engine(dbPath)
                        result.success(null)
                    } catch (e: Exception) {
                        result.error("INIT_ERROR", e.message, null)
                    }
                }
                "getOrCompute" -> {
                    val key = call.argument<String>("key")!!
                    val ttl = call.argument<Int>("ttlSeconds")!!
                    val taskType = call.argument<String>("taskType")!!
                    val input = call.argument<ByteArray>("input")!!

                    nativeEngine?.getOrCompute(key, ttl.toLong(), taskType, input, object : Callback {
                        override fun onSuccess(data: ByteArray?) {
                            runOnUiThread {
                                result.success(data)
                            }
                        }

                        override fun onError(error: String?) {
                            runOnUiThread {
                                result.error("COMPUTE_ERROR", error, null)
                            }
                        }
                    }) ?: result.error("NOT_INITIALIZED", "Engine not initialized", null)
                }
                "flushCache" -> {
                    nativeEngine?.flushCache()
                    result.success(null)
                }
                "getStats" -> {
                    result.success(nativeEngine?.stats)
                }
                "dispose" -> {
                    nativeEngine?.close()
                    nativeEngine = null
                    result.success(null)
                }
                else -> result.notImplemented()
            }
        }
    }
}
